apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: chatgpt-web-node
  name: chatgpt-web-node
spec:
  replicas: 3
  selector:
    matchLabels:
      name: chatgpt-web-node
  template:
    metadata:
      labels:
        name: chatgpt-web-node
    spec:
      containers:
      - image: gcr.io/fake-playground/chatgpt-web:v1.0
        name: chatgpt-web-node
        env:
          - name: OPENAI_API_KEY
            value: <your-api-key>
        ports:
        - containerPort: 3002
