apiVersion: v1
kind: Service
metadata:
  labels:
    name: chatgpt-web-service
  name: chatgpt-web-service
spec:
  ports:
    - port: 3002
      nodePort: 31002
  selector:
    name: chatgpt-web-node
  type: LoadBalancer